name: tech_shift
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  awesome_snackbar_content: ^0.1.4
  bloc: ^8.1.4
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.4.4
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  lottie: ^3.1.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/how_it_works/
    - assets/why_choose_us/
    - assets/displayimage/
