name: tech_shift
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  animate_do: ^3.3.4
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_storage: ^12.3.7
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.6
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  lottie: ^3.1.3
  pinput: ^5.0.1
  rxdart: ^0.28.0
  simple_animations: ^5.1.0
  wakelock_plus: ^1.2.10

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/testimg/
    - assets/fonts/
